language: php
sudo: false

cache:
  directories:
  - $HOME/.composer/cache/files

jobs:
  fast_finish: true
  include:
  - php: 7.1
    env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
  - php: 7.2
    env: COVERAGE=true DEPENDENCIES="friends-of-phpspec/phpspec-code-coverage:^4.3 phpspec/phpspec:^5.1"
    script:
    - composer test-ci
    after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml --revision=$TRAVIS_COMMIT
    # Test LTS versions
  - php: 7.2
    env: DEPENDENCIES="dunglas/symfony-lock:^3"
  - php: 7.2
    env: DEPENDENCIES="dunglas/symfony-lock:^4"
  - php: 7.2
    env: TEST_COMMAND="./vendor/bin/phpunit" DEPENDENCIES="phpunit/phpunit:^7.5 nyholm/psr7:^1.0"

    # Latest dev release
  - php: 7.4
    env: STABILITY="dev"

before_install:
- if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
- if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
- if ! [ -z "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
- cat composer.json
# To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
- if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
- composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
- composer validate --strict --no-check-lock
- composer test
